# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
coverage:
  range: 50..80
  round: down
  precision: 2
  status:
    project:
      default:
        target: 72%
ignore:
  - "*_test.go"
  - "vendor"
  - "internal/quic/redirect.go"
  - "internal/quic/dial.go"
  - "internal/quic/cmd/example/main.go"
