# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
version: "2"
linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - goconst
    - gosec
    - misspell
    - prealloc
    - unconvert
  disable:
    - errcheck
    - ineffassign
  settings:
    errorlint:
      errorf: false
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
        path: _test.go
      - linters:
          - gosec
        path: internal/credentials/cmd/example/main.go
      - linters:
          - bodyclose
          - errorlint
          - goconst
          - gosec
          - govet
          - misspell
          - prealloc
          - staticcheck
        path: internal/nhooyr.io/*
    paths:
      - internal/jwtxt/keypairs_for_test.go
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
