# SPDX-FileCopyrightText: 2024 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
project_name: xmidt-agent

version: 2

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: 'Dependency Updates'
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation Updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other Work
      order: 9999

sboms:
  - id: archive
    artifacts: archive
  - id: source
    artifacts: source

builds:
  -
    main:  './cmd/xmidt-agent'
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - mips
      - mips64
      - mips64le
      - mipsle
    goarm:
      - "5"
      - "6"
      - "7"
    ldflags:
      - -s -w
    mod_timestamp: "{{ .CommitTimestamp }}"

upx:
  -
    enabled: true
    compress: best
    lzma: true

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

nfpms:
  -
    id: rdk
    file_name_template: '{{ .PackageName }}_{{ .Version }}_rdk_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    vendor: xmidt-org
    homepage: https://github.com/xmidt-org/xmidt-agent
    license: Apache-2.0
    maintainer: see_maintainers_file@example.com
    description: The client agent for the Xmidt service.

    formats:
      - ipk

    dependencies:
      - systemd

    contents:
      # systemd service file
      - src: .release/ipk/xmidt-agent.service
        dst: /lib/systemd/system/xmidt-agent.service

      # base configuration file
      - src: .release/ipk/config.yml
        dst: /etc/xmidt-agent/conf.d/01-config.yml

    scripts:
      preinstall: .release/ipk/preinstall.sh
      postinstall: .release/ipk/postinstall.sh

    ipk:
      fields:
        Bugs: https://github.com/xmidt-org/xmidt-agent/issues

  -
    id: openwrt
    file_name_template: '{{ .PackageName }}_{{ .Version }}_openwrt_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    vendor: xmidt-org
    homepage: https://github.com/xmidt-org/xmidt-agent
    license: Apache-2.0
    maintainer: see_maintainers_file@example.com
    description: The client agent for the Xmidt service.

    formats:
      - ipk

    contents:
      # base configuration file
      - src: .release/ipk/config.yml
        dst: /etc/xmidt-agent/conf.d/01-config.yml

    ipk:
      fields:
        Bugs: https://github.com/xmidt-org/xmidt-agent/issues

  -
    id: server
    file_name_template: '{{ .PackageName }}_{{ .Version }}_debian_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    vendor: xmidt-org
    homepage: https://github.com/xmidt-org/xmidt-agent
    license: Apache-2.0
    maintainer: see_maintainers_file@example.com
    description: The client agent for the Xmidt service.

    formats:
      - deb
      - rpm

    contents:
      # base configuration file
      - src: .release/ipk/config.yml
        dst: /etc/xmidt-agent/conf.d/01-config.yml

    deb:
      signature:
        key_file: .secrets/deb_gpg_private_key_file
      fields:
        Bugs: https://github.com/xmidt-org/xmidt-agent/issues
    rpm:
      group: System Environment/Daemons
      signature:
        key_file: .secrets/rpm_gpg_private_key_file

source:
  enabled: true
  name_template: '{{ .ProjectName }}_{{ .Version }}_src'
  format: 'tar.gz'

checksum:
  name_template: '{{.ProjectName}}-{{.Version}}-checksums.txt'
  algorithm: sha256

release:
  extra_files:
    - glob: ./.extra_files/**

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.url=https://github.com/xmidt-org/xmidt-agent"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.source=https://github.com/xmidt-org/xmidt-agent"
      - "--label=org.opencontainers.image.version={{.Version}}"
    image_templates:
      - ghcr.io/xmidt-org/xmidt-agent:{{ .Tag }}-amd64
      - ghcr.io/xmidt-org/xmidt-agent:v{{ .Major }}-amd64
      - ghcr.io/xmidt-org/xmidt-agent:v{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/xmidt-org/xmidt-agent:latest-amd64
    dockerfile: 'Dockerfile'
    extra_files:
      - .release/docker
      - LICENSE
      - NOTICE
