# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
      - MAINTAINERS.md
      - LICENSE
      - NOTICE
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    uses: xmidt-org/shared-go/.github/workflows/ci.yml@c1c3acacf1c0a4ee7852b0d41c1174f52fa412e9 # v4.9.33
    with:
      release-type:         program
      release-main-package: ./cmd/xmidt-agent
      release-custom-file:  true
      release-docker:       true
      yaml-lint-skip:       false
    secrets: inherit
